image_width: 640
image_height: 480
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [821.63174,   0.     , 309.42727,
           0.     , 820.98395, 227.77095,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.436078, -1.296308, -0.018553, -0.009690, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [857.58574,   0.     , 305.36998,   0.     ,
           0.     , 855.32401, 222.56392,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
